---

# Multiple tasks will need the output of RPM verification, so let's do the
# lookup one time and then grep over the output in subsequent tasks.
- name: Verify all installed RPM packages
  shell: "rpm -Va > {{ temp_dir }}/rpmverify.txt"
  args:
    warn: no
  failed_when: False
  changed_when: False
  register: rpmverify_task
  async: 300
  poll: 0
  when:
    - not check_mode | bool
    - ansible_os_family | lower in ['redhat', 'suse']
  tags:
    - rpm
    - high
    - V-71855
    - skip_ansible_lint

- name: Check for .shosts or shosts.equiv files
  find:
    paths: /
    recurse: yes
    hidden: yes
    patterns: '.shosts,shosts.equiv'
  changed_when: False
  register: shosts_find
  async: 300
  poll: 0
  when:
    - not check_mode | bool
    - security_rhel7_remove_shosts_files | bool
  tags:
    - high
    - auth
    - V-72277
    - V-72279
