---

- include_tasks: rpm.yml

- name: Check if /etc/yum/yum-cron.conf exists
  stat:
    path: /etc/yum/yum-cron.conf
  check_mode: no
  register: yum_cron_config_check
  when:
    - ansible_os_family | lower == 'redhat'
  tags:
    - always

- name: Enable automatic package updates (yum)
  lineinfile:
    dest: /etc/yum/yum-cron.conf
    regexp: "^apply_updates"
    line: "apply_updates = yes"
    state: present
  when:
    - ansible_os_family | lower == 'redhat'
    - yum_cron_config_check.stat.exists | bool
    - security_rhel7_automatic_package_updates | bool
  tags:
    - packages
    - medium
    - V-71999
