---

# Restarting services ########################################################
#
# NOTE(mhayden): It's not possible to use systemd to restart auditd on CentOS
# since it's a special service. Using the old service scripts is required.
- name: restart auditd
  command: service auditd restart
  args:
    warn: no

- name: restart chrony
  service:
    name: "{{ chrony_service }}"
    state: restarted

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: restart postfix
  service:
    name: postfix
    state: restarted

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: restart samba
  service:
    name: smbd
    state: restarted

- name: restart ssh
  service:
    name: "{{ ssh_service }}"
    state: restarted

- name: restart vsftpd
  service:
    name: vsftpd
    state: restarted

- name: restart clamav
  service:
    name: "{{ clamav_service }}"
    state: restarted

# Miscellaneous ##############################################################
- name: generate auditd rules
  command: augenrules --load
  notify: restart auditd

- name: rehash aliases
  command: newaliases

- name: update grub config
  command: "{{ grub_update_cmd }}"
  when:
    - (security_enable_grub_update | bool) or (security_require_grub_menu_authentication | bool)
    - grub_update_binary.stat.exists | bool
    - grub_update_binary.stat.executable | bool
  notify:
    - set bootloader file permissions after updating grub config

# NOTE(mhayden): Running `update-grub` causes the bootloader permissions to
# change, which breaks V-38583.
- name: set bootloader file permissions after updating grub config
  file:
    path: "{{ grub_config_file_boot }}"
    mode: "0644"

- name: dconf update
  command: dconf update

- name: reload systemd
  systemd:
    daemon-reload: yes
